######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QMAKE_CXXFLAGS += -std=c++0x

# Input
HEADERS += main.hh
SOURCES += main.cc
